model:
  class_path: src.model.SVEBM
  init_args:
    ebm_model:
      class_path: src.prior.ebm_model.ebm_model
      init_args:
        hidden_layers: [100, 100]
        activation: relu
        input_dim: 100
        output_dim: 100
    encoder_model:
      class_path: src.posterior.encoder_model.encoder_model
      init_args:
        hidden_layers: [100, 100]
        activation: relu
        input_dim: 100
        output_dim: 100
    decoder_model:
      class_path: src.posterior.decoder_model.decoder_model